stages:
  - build
  - test
  - analyze
  - commit_info
  - lint

# Etapa de Testes: Rodar os testes do Flutter
flutter_tests:
  stage: test
  script:
    - flutter test

# Etapa de Build: Compilar o APK
build_app:
  stage: build
  script:
    - flutter pub get
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk

# Etapa de Análise de Código: Rodar flutter analyze
analyze_code:
  stage: analyze
  script:
    - flutter analyze

# Etapa de Lints: validação das regras definidas
lint_check:
  stage: lint
  script:
    - echo "Rodando lints com flutter analyze"
    - flutter analyze

# Etapa de Identificação do Commit: Exibir o commit atual
commit_info:
  stage: commit_info

